### ISSUE TITLE
Internal class with parameters union type fail (php8)

### ISSUE THREAD

**Issue by fezfez** [laminas/laminas-code#53]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.5.0

#### Summary

Internal class with parameters union type fail (php8)

#### Current behavior
Exception with union type parameter

```
PHP Fatal error:  Uncaught Laminas\Code\Generator\Exception\InvalidArgumentException: Provided type "array|string|null" is invalid: must conform "/^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*(\\[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*)*$/" in /var/www/src/Generator/TypeGenerator.php:74
Stack trace:
#0 /var/www/src/Generator/ParameterGenerator.php(185): Laminas\Code\Generator\TypeGenerator::fromTypeString('array|string|nu...')
#1 /var/www/src/Generator/ParameterGenerator.php(67): Laminas\Code\Generator\ParameterGenerator->setType('array|string|nu...')
#2 /var/www/test.php(8): Laminas\Code\Generator\ParameterGenerator::fromReflection(Object(Laminas\Code\Reflection\ParameterReflection))
#3 {main}
  thrown in /var/www/src/Generator/TypeGenerator.php on line 74
```

#### How to reproduce
```php
<?php

use Laminas\Code\Generator\ParameterGenerator;
use Laminas\Code\Reflection\ParameterReflection;

require 'vendor/autoload.php';

$parameter = ParameterGenerator::fromReflection(new ParameterReflection([\Phar::class, 'extractTo'], 1));
```

**Comment by Ocramius** [comment]
@fezfez please review #57 when you have time :-)

**Comment by Ocramius** [comment]
Closing here, as it's being discussed in #57
